sudo: required
language: python3
services:
- docker
git:
  depth: 5
branches:
  only:
  - "/^(?i:SWIK)-.*$/"
  - master
install: true
script:
- echo skipping
after_success:
- openssl aes-256-cbc -K $encrypted_390cee1cf48d_key -iv $encrypted_390cee1cf48d_iv
  -in .travis/deployment_keys.tar.enc -out deployment_keys.tar -d
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then
  ./travis_scripts/dockerhub.sh ; fi
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then
  ./travis_scripts/deploy.sh ; fi
after_script:
- rm -f deployment_keys.tar
- rm -f ~/.docker/{cert,key,ca}.pem
env:
  global:
  - secure: Ik2TBZGhuYEn+7JUo/WcqL8YXs9xvD0GQlhpQS82wYHlLyvVU6S6Je4km5XQTQVATx4TavrgXt6kleVfm1qFkqZv1VBN+ggS0bh5ZXgiuvxiP5GnzSXqVIIoUmIVm6U3/merRSAdOfF+lW12VXA08bsSwv/7quMv7FkyK2WjjOS5i8fEo4R3YGV2+kgpzBU8ZT8hTG8A4XKBe1Lr+80eV1IfweAxn2uA4NZlI8yAK9q60wxKSqITzuTqOe1GjzGCKGUtos6vIojcOzlCo95FT+HFBpJkL05Tml4htPWFCBdebt2szU4J0BikMGkhTe+1gbuuvC93SRk6BexT48zmtm0OoZ2fY9v9hhYA/1Bv0FaCtjk/fvUiqw/ODGggm0/iOUKPkwdx5QVN8xzse8sjsme1QxL3XzXYNewCKDDT+1fVDOSn8hLP6qYTNPU2IRcao/etc51vMxRPPk++bSpP0bEwf6qy3uBiufpcrhtN63oKNn5a5gFpzDh2NeHlPpdPwsm1s7ZLsrJw1qGesjVDLDkj+mvtjOGcoQByxImmjm+9IDTjh0s5z0d/lkbxVGQoDcC7jAj3BMNnocBkX4qZQc6fev5TuUYX6LBVuGZ3EkchUOMp/x40Tqrw6n7fHUdbXvTgAfzOTlihikcs4isvXRapHgYtNJ7yhI6W35sWU4o=
  - secure: DitNzp+vquc3RceUMfx/ieX3W1uXk+Rk6Ofx1Uoc9KJuMIUzTHkUF7aQImGE77pIM3Ahy+dtFbhI21Nuhd5JbKlNvOSnVDHRdp9o/kc55+igXOnV+N7u0ODSesDUzxcwjiaoIqYWRfLlLBIPW7yIaGnP5JNxK5dbcpfCVka1UzvOm6fo1cDnhElBUhjreRZ8uI4FGvOp3fGPyr4+I5Zu/28aIGiEy0X0f6gUo6Wrf/lmRpNz+aoTB9wI3RyL9VktktZ69FeM+VGDlrs6qH5sVxcdZ8BLEk9+WCt1KAQ9nl6MkG7vyEJBbDKvNbArsvNSKbMJIERsnAZTq8Dp3Vc8a71kIVoWMCJXgNM/7WbShmptbuWGbYY2UFSBztNMAS9IJNuPUhSQnqISGm5Izs9QAD7AWnthDj4jrKygw29UIrTv0odrhMZ8SOlZDzdc7wC6eMlw6jpxDd0x//SNlTAFNRNeeaS9/xFMXJW7RiMu9Ex9RSn7yz0tTnjR3Xt1hVPG8x/B673T8j41z6YP42mvRTeL11hlVFNrkST7ux15JHeOXVYyy3rHZTpy0N3q3w8lMm9bqB3GV2+aKo1LM4f2OzHoBLPilqlgGKglNeRvLW3+nt8MTrbbfJO4fpQbh21mIdXHZmH+bn05mhTIUoldknTkuDtxQmkJgCNNdvhtCR0=
  - secure: BkJQkWa+T3rKhaVLzj28ATO6BsTKBrY5eKN78vrzZl/HMAuz8bl4qQafl0jR23mYXIrgLVXVigMtgkpP+Y0lIBTMfXeQY0SNyf/wW9O1TtnduWKX6pi+ziO0xeI96w2EK4NFKK6RYxsfn7hdMpo+8jJHQeCG9WF/nBTztHB5XA4LdLZhuwdtpMQjmOq301ETXl90s6OlVNHjEPbk3GxV5Azjzxn84R5zuSlQn74CnUC775OsukGwOZ+1wM4pZmYlhA6j0qAA64zsf3qnra0LrPEevGB+60t824gwMlTyGErsJ5cFLgUxW4ns3xcqR0FXD4wpsumlwRpPtJAbO+a6eaEZ0MkryA2CcNZoOapdNYrOvbYB/4xuBwuBUTlrdMWldixV315Edzzlr0fn+qQmVJ2bbQuuSslVrX8Tovph5ZaXaFpLwf2Z2/6hNW9CMCQpsuDGKhsCYbLeng0rwMMzZfbaDzAnYCN3FmZgM2Nz5Q5SNVloyi0yR/iak5+B99aWhdKK2PdbsE8seYloEvQFbh6Tj0yzyV4M13ds4QYtgSNz0HEGx3ZRMMf+KwDuPpbhva3ctVhqI2+0rMJFv5Dc1S1cL2QboHsULRdXqmOBX5N2K4ulshUhRdiaPBJiE0dCp96zPXnJiyGnRQD3hoR/vXuoCVR+lktlutrsZhEYiCM=
