sudo: required
language: python
python:
- "3.6"
services:
- docker
git:
  depth: 5
branches:
  only:
  - "/^(?i:SWIK)-.*$/"
  - master
install: true
script:
- python setup.py install
after_success:
- openssl aes-256-cbc -K $encrypted_390cee1cf48d_key -iv $encrypted_390cee1cf48d_iv
  -in .travis/deployment_keys.tar.enc -out deployment_keys.tar -d
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then
  .travis/dockerhub.sh ; fi
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then
  .travis/deploy.sh ; fi
after_script:
- rm -f deployment_keys.tar
- rm -f ~/.docker/{cert,key,ca}.pem
env:
  global:
  - secure: JohkwvHoJlYI8CbMkKIPmvs7/bNpolJiz5VRCKkNHhOTzAB160FvsMJiqPathm5EqB4GCpx/KHRqbcDmkeomYF++XHSwSIDKPrqZswaRQDh0JIV8eWgVKUHZYWXZ8/UGXAY5Rk6iGm5sWYSHIRFqOe+9sa6NweVq5/0itweL4GOYUPVc4skCoSxfFvc1SUjsYBpSioJe41OmoClnPkCK5WZDfDbZgXfF4Fg16mvWEN2chAt+K8wl/FZh/IkLbb3dNsttGDXa2wqq+IsI/1BNlJOB/yTjTeURt3w8pdZ09+DN6MPO1FvgG9GCNMLY1hAi+IWkAWWR0+mhWqr4T3G/MA8iyY2oXNbU5W+xQMpTScO7Rwn1TufznNXI0qtIdhnQHI4c1vEpbWkVgxu47CEHNXtEJKYmFgW5RZHFxyYAZDDzDhjSC3aDEhGW/nQtwg7ydxxUX7aZlo8ogYHHw9MFLEmny5OykvX+RBaJym7ly+LJIi4wBDb6pO2TQlD/5YNszqJqz745ulaXnkIVbgeKqGgnI+d8vRjAmpgeMYJYpUg13wUsCOWsYacNnJiuT1JGbkerkX7ufwETtVXR7dhPVoxnxcJE9QRBaydxESEgN/rHoyjz3r0CMlBxCVmOkbX7f1PuhXEyfcYDI6vlp8JyRVhiHhKzH7c+fy98x1/R6zo=
  - secure: DitNzp+vquc3RceUMfx/ieX3W1uXk+Rk6Ofx1Uoc9KJuMIUzTHkUF7aQImGE77pIM3Ahy+dtFbhI21Nuhd5JbKlNvOSnVDHRdp9o/kc55+igXOnV+N7u0ODSesDUzxcwjiaoIqYWRfLlLBIPW7yIaGnP5JNxK5dbcpfCVka1UzvOm6fo1cDnhElBUhjreRZ8uI4FGvOp3fGPyr4+I5Zu/28aIGiEy0X0f6gUo6Wrf/lmRpNz+aoTB9wI3RyL9VktktZ69FeM+VGDlrs6qH5sVxcdZ8BLEk9+WCt1KAQ9nl6MkG7vyEJBbDKvNbArsvNSKbMJIERsnAZTq8Dp3Vc8a71kIVoWMCJXgNM/7WbShmptbuWGbYY2UFSBztNMAS9IJNuPUhSQnqISGm5Izs9QAD7AWnthDj4jrKygw29UIrTv0odrhMZ8SOlZDzdc7wC6eMlw6jpxDd0x//SNlTAFNRNeeaS9/xFMXJW7RiMu9Ex9RSn7yz0tTnjR3Xt1hVPG8x/B673T8j41z6YP42mvRTeL11hlVFNrkST7ux15JHeOXVYyy3rHZTpy0N3q3w8lMm9bqB3GV2+aKo1LM4f2OzHoBLPilqlgGKglNeRvLW3+nt8MTrbbfJO4fpQbh21mIdXHZmH+bn05mhTIUoldknTkuDtxQmkJgCNNdvhtCR0=
  - secure: BkJQkWa+T3rKhaVLzj28ATO6BsTKBrY5eKN78vrzZl/HMAuz8bl4qQafl0jR23mYXIrgLVXVigMtgkpP+Y0lIBTMfXeQY0SNyf/wW9O1TtnduWKX6pi+ziO0xeI96w2EK4NFKK6RYxsfn7hdMpo+8jJHQeCG9WF/nBTztHB5XA4LdLZhuwdtpMQjmOq301ETXl90s6OlVNHjEPbk3GxV5Azjzxn84R5zuSlQn74CnUC775OsukGwOZ+1wM4pZmYlhA6j0qAA64zsf3qnra0LrPEevGB+60t824gwMlTyGErsJ5cFLgUxW4ns3xcqR0FXD4wpsumlwRpPtJAbO+a6eaEZ0MkryA2CcNZoOapdNYrOvbYB/4xuBwuBUTlrdMWldixV315Edzzlr0fn+qQmVJ2bbQuuSslVrX8Tovph5ZaXaFpLwf2Z2/6hNW9CMCQpsuDGKhsCYbLeng0rwMMzZfbaDzAnYCN3FmZgM2Nz5Q5SNVloyi0yR/iak5+B99aWhdKK2PdbsE8seYloEvQFbh6Tj0yzyV4M13ds4QYtgSNz0HEGx3ZRMMf+KwDuPpbhva3ctVhqI2+0rMJFv5Dc1S1cL2QboHsULRdXqmOBX5N2K4ulshUhRdiaPBJiE0dCp96zPXnJiyGnRQD3hoR/vXuoCVR+lktlutrsZhEYiCM=
