recommenderservice:
  image: slidewiki/recommenderservice:latest-dev
  restart: on-failure:5
  environment:
    - VIRTUAL_HOST=recommenderservice.experimental.slidewiki.org
    - FLASK_SERVER_NAME=recommenderservice.experimental.slidewiki.org
    - SERVICE_URL_DECK=https://deckservice.experimental.slidewiki.org
    - SERVICE_URL_USER=https://userservice.experimental.slidewiki.org
    - SERVICE_URL_ACTIVITIES=https://activitiesservice.experimental.slidewiki.org
    - SERVICE_URL_NLP=https://nlpservice.experimental.slidewiki.org
    - LETSENCRYPT_HOST=recommenderservice.experimental.slidewiki.org
    - LETSENCRYPT_EMAIL=meissner@informatik.uni-leipzig.de
