recommender-service:
  image: slidewiki/recommender-service:latest-dev
  restart: on-failure:5
  expose:
    - "80"
  environment:
    - APPLICATION_PORT=80
    - VIRTUAL_HOST=recommenderservice.experimental.slidewiki.org
    - SERVICE_URL_DECK=https://deckservice.experimental.slidewiki.org
    - LETSENCRYPT_HOST=recommenderservice.experimental.slidewiki.org
    - LETSENCRYPT_EMAIL=meissner@informatik.uni-leipzig.de
